name: Post Approved

on:
  issue_comment:
    types: [created]

concurrency:
  group: autopost-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write

jobs:
  post:
    if: contains(github.event.comment.body, 'approve:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Noto fonts
        run: sudo apt-get update && sudo apt-get install -y fonts-noto-cjk
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Post approved candidates
        env:
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
          X_MEDIA_STRATEGY: ${{ vars.X_MEDIA_STRATEGY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node dist/cli/post.js
